sonar.projectKey=api-gateway
sonar.projectName=API Gateway - Grupo Cordillera
sonar.projectVersion=1.0


sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

sonar.host.url=http://localhost:9000

sonar.token=squ_cc1ff940aeabf06d19feec5039bbdd29b9d9f672